const SOCIALS = [
  ['facebook','Facebook','fb'],['instagram','Instagram','ig'],['linkedin','LinkedIn','in'],['tiktok','TikTok','tt'],['youtube','YouTube','yt'],['telegram','Telegram','tg'],['x','X','x'],['github','GitHub','gh'],['snapchat','Snapchat','snap'],['discord','Discord','discord'],['threads','Threads','threads'],['pinterest','Pinterest','pin']
];
const ICONS = ['i1','i2','i3','i4','i5','i6','ck'];
const json = (data, status=200, headers={}) => new Response(JSON.stringify(data), {status, headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin',...headers}});
const fail = (msg, status=400) => json({error:msg},status);
const b64 = bytes => btoa(String.fromCharCode(...new Uint8Array(bytes)));
const unhex = s => new Uint8Array((s.match(/.{1,2}/g)||[]).map(x=>parseInt(x,16)));
const hex = bytes => [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,'0')).join('');
async function digest(s){return hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));}
async function hashPassword(password, saltHex){const salt=saltHex?unhex(saltHex):crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:100000,hash:'SHA-256'},key,256);return `${hex(salt)}:${hex(bits)}`;}
async function verifyPassword(password, stored){if(!stored)return false;const [salt,expected]=stored.split(':');const actual=(await hashPassword(password,salt)).split(':')[1];return actual.length===expected.length && [...actual].reduce((a,c,i)=>a|(c.charCodeAt(0)^expected.charCodeAt(i)),0)===0;}
async function bodyJson(req){try{return await req.json()}catch{return null}}
function cookieVal(req){return (req.headers.get('Cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('cr_admin='))?.slice(9)||'';}
function setCookie(token,maxAge){return `cr_admin=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`;}
function originOk(req){const o=req.headers.get('Origin');return !o || new URL(o).host===new URL(req.url).host;}
async function session(req,env){const token=decodeURIComponent(cookieVal(req));if(!token)return null;const row=await env.DB.prepare('SELECT csrf,expires_at FROM sessions WHERE token_hash=?').bind(await digest(token)).first();if(!row||row.expires_at<Date.now()){if(row)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await digest(token)).run();return null;}return {token,csrf:row.csrf};}
async function setting(env,key,fallback=''){const r=await env.DB.prepare('SELECT value FROM settings WHERE key=?').bind(key).first();return r?r.value:fallback;}
async function setSetting(env,key,value){await env.DB.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(key,String(value)).run();}
async function publicData(env){const services=(await env.DB.prepare('SELECT * FROM services WHERE visible=1 ORDER BY sort_order,id').all()).results.map(s=>({title:s.title,desc:s.description,icon:s.icon,cta:'ابدأ الطلب',img:'',on:true}));const certificates=(await env.DB.prepare('SELECT * FROM certificates WHERE visible=1 ORDER BY sort_order,id').all()).results.map(c=>({title:c.title,desc:c.description,img:c.image,on:true}));const number=await setting(env,'whatsapp_number','971541494114'),email=await setting(env,'email'),saved=JSON.parse(await setting(env,'socials','{}')||'{}');const socials=[{name:'WhatsApp',key:'whatsapp',icon:'wa',url:number?'https://wa.me/'+number:'',on:true},...SOCIALS.map(([key,name,icon])=>({name,key,icon,url:(saved[key]||{}).url||'',on:(saved[key]||{}).on!==false})),{name:'Email',key:'email',icon:'mail',url:email?'mailto:'+email:'',on:true}];return {services,certificates,contact:{phone:await setting(env,'phone'),whatsapp:number,email,address:await setting(env,'address'),hours:await setting(env,'hours'),waMsg:await setting(env,'wa_message','مرحباً، أريد بدء معاملة مع CAPITAL RISE')},socials};}
async function list(env,table){return (await env.DB.prepare(`SELECT * FROM ${table} ORDER BY sort_order,id`).all()).results;}
async function reorder(env,table,id,dir){const rows=await list(env,table);const i=rows.findIndex(r=>r.id===id),j=dir==='up'?i-1:i+1;if(i<0||j<0||j>=rows.length)return;[rows[i],rows[j]]=[rows[j],rows[i]];for(let n=0;n<rows.length;n++)await env.DB.prepare(`UPDATE ${table} SET sort_order=? WHERE id=?`).bind(n+1,rows[n].id).run();}
export async function onRequest({request,env}){const u=new URL(request.url),p=u.pathname,m=request.method;try{
 if(p==='/api/public'&&m==='GET')return json(await publicData(env));
 if(p.startsWith('/api/uploads/')&&m==='GET'){const name=p.slice(13);if(!/^[a-f0-9]{32}\.(png|jpg|webp|gif)$/.test(name))return fail('غير موجود',404);const row=await env.DB.prepare('SELECT mime,data FROM uploads WHERE name=?').bind(name).first();return row?new Response(row.data,{headers:{'Content-Type':row.mime,'Cache-Control':'public,max-age=31536000,immutable','X-Content-Type-Options':'nosniff'}}):fail('غير موجود',404);}
 if(p==='/api/admin/login'&&m==='POST'){if(!originOk(request))return fail('طلب مرفوض',403);const b=await bodyJson(request);if(!b)return fail('بيانات غير صحيحة');if(String(b.username||'')!==(env.ADMIN_USERNAME||'admin'))return fail('اسم المستخدم أو كلمة المرور غير صحيحة',401);const saved=await setting(env,'admin_password_hash','');let ok=false;if(saved)ok=await verifyPassword(String(b.password||''),saved);else ok=!!env.ADMIN_PASSWORD&&String(b.password||'')===String(env.ADMIN_PASSWORD);if(!ok){await new Promise(r=>setTimeout(r,350));return fail('اسم المستخدم أو كلمة المرور غير صحيحة',401);}if(!saved)await setSetting(env,'admin_password_hash',await hashPassword(String(b.password)));const token=hex(crypto.getRandomValues(new Uint8Array(32))),csrf=hex(crypto.getRandomValues(new Uint8Array(24))),now=Date.now();await env.DB.prepare('INSERT INTO sessions(token_hash,csrf,created_at,expires_at) VALUES(?,?,?,?)').bind(await digest(token),csrf,now,now+12*3600*1000).run();return json({ok:true},200,{'Set-Cookie':setCookie(token,43200)});}
 if(p.startsWith('/api/admin/')){const s=await session(request,env);if(!s)return fail('انتهت الجلسة. سجّل الدخول من جديد.',401);if(m!=='GET'&&(!originOk(request)||request.headers.get('X-CSRF-Token')!==s.csrf))return fail('طلب مرفوض',403);
 if(p==='/api/admin/me'&&m==='GET')return json({username:env.ADMIN_USERNAME||'admin',csrf:s.csrf});
 if(p==='/api/admin/logout'&&m==='POST'){await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await digest(s.token)).run();return json({ok:true},200,{'Set-Cookie':setCookie('',0)});}
 if(p==='/api/admin/password'&&m==='POST'){const b=await bodyJson(request);const saved=await setting(env,'admin_password_hash','');const ok=saved?await verifyPassword(String(b?.current||''),saved):(!!env.ADMIN_PASSWORD&&String(b?.current||'')===String(env.ADMIN_PASSWORD));if(!ok)return fail('كلمة المرور الحالية غير صحيحة',403);if(String(b?.next||'').length<10)return fail('كلمة المرور الجديدة يجب ألا تقل عن 10 أحرف');await setSetting(env,'admin_password_hash',await hashPassword(String(b.next)));return json({ok:true});}
 if(p==='/api/admin/services'&&m==='GET')return json((await list(env,'services')).map(r=>({id:r.id,title:r.title,description:r.description,icon:r.icon,visible:!!r.visible,order:r.sort_order})));
 if(p==='/api/admin/services'&&m==='POST'){const b=await bodyJson(request);if(!String(b?.title||'').trim())return fail('اسم الخدمة مطلوب');const max=(await env.DB.prepare('SELECT COALESCE(MAX(sort_order),0)+1 n FROM services').first()).n;const r=await env.DB.prepare('INSERT INTO services(title,description,icon,visible,sort_order) VALUES(?,?,?,?,?)').bind(String(b.title).trim().slice(0,120),String(b.description||'').slice(0,1000),ICONS.includes(b.icon)?b.icon:'i1',b.visible===false?0:1,max).run();return json({id:r.meta.last_row_id,title:String(b.title).trim(),description:String(b.description||''),icon:ICONS.includes(b.icon)?b.icon:'i1',visible:b.visible!==false,order:max},201);}
 let match=p.match(/^\/api\/admin\/(services|certificates)\/(\d+)(\/move)?$/);if(match){const table=match[1],id=Number(match[2]),isSvc=table==='services';const t=isSvc?'services':'certificates',row=await env.DB.prepare(`SELECT * FROM ${t} WHERE id=?`).bind(id).first();if(!row)return fail('العنصر غير موجود',404);if(match[3]&&m==='POST'){const b=await bodyJson(request);await reorder(env,t,id,b?.dir==='up'?'up':'down');return json((await list(env,t)).map(r=>isSvc?{id:r.id,title:r.title,description:r.description,icon:r.icon,visible:!!r.visible,order:r.sort_order}:{id:r.id,title:r.title,description:r.description,image:r.image,visible:!!r.visible,order:r.sort_order}));}if(m==='PUT'){const b=await bodyJson(request);const title=b.title===undefined?row.title:String(b.title).slice(0,120),description=b.description===undefined?row.description:String(b.description).slice(0,isSvc?1000:600),visible=b.visible===undefined?row.visible:(b.visible?1:0);if(isSvc)await env.DB.prepare('UPDATE services SET title=?,description=?,icon=?,visible=? WHERE id=?').bind(title,description,ICONS.includes(b.icon)?b.icon:row.icon,visible,id).run();else await env.DB.prepare('UPDATE certificates SET title=?,description=?,image=?,visible=? WHERE id=?').bind(title,description,b.image===undefined?row.image:String(b.image),visible,id).run();const r=await env.DB.prepare(`SELECT * FROM ${t} WHERE id=?`).bind(id).first();return json(isSvc?{id:r.id,title:r.title,description:r.description,icon:r.icon,visible:!!r.visible,order:r.sort_order}:{id:r.id,title:r.title,description:r.description,image:r.image,visible:!!r.visible,order:r.sort_order});}if(m==='DELETE'){await env.DB.prepare(`DELETE FROM ${t} WHERE id=?`).bind(id).run();if(!isSvc&&row.image)await env.DB.prepare('DELETE FROM uploads WHERE name=?').bind(row.image.split('/').pop()).run();return json({ok:true});}}
 if(p==='/api/admin/certificates'&&m==='GET')return json((await list(env,'certificates')).map(r=>({id:r.id,title:r.title,description:r.description,image:r.image,visible:!!r.visible,order:r.sort_order})));
 if(p==='/api/admin/certificates'&&m==='POST'){const b=await bodyJson(request);if(!b?.image)return fail('اختر صورة الشهادة أولًا');const max=(await env.DB.prepare('SELECT COALESCE(MAX(sort_order),0)+1 n FROM certificates').first()).n;const title=String(b.title||'').slice(0,120),description=String(b.description||'').slice(0,600);const r=await env.DB.prepare('INSERT INTO certificates(title,description,image,visible,sort_order) VALUES(?,?,?,?,?)').bind(title,description,String(b.image),b.visible===false?0:1,max).run();return json({id:r.meta.last_row_id,title,description,image:String(b.image),visible:b.visible!==false,order:max},201);}
 if(p==='/api/admin/upload'&&m==='POST'){const buf=await request.arrayBuffer();if(buf.byteLength>1400000)return fail('حجم الصورة الأقصى 1.4 ميجابايت في النسخة المجانية');const a=new Uint8Array(buf);let mime='',ext='';if(a[0]===137&&a[1]===80&&a[2]===78&&a[3]===71){mime='image/png';ext='png';}else if(a[0]===255&&a[1]===216&&a[2]===255){mime='image/jpeg';ext='jpg';}else if(a[0]===71&&a[1]===73&&a[2]===70){mime='image/gif';ext='gif';}else if(a[0]===82&&a[1]===73&&a[2]===70&&a[8]===87&&a[9]===69&&a[10]===66&&a[11]===80){mime='image/webp';ext='webp';}else return fail('استخدم صورة PNG أو JPG أو WEBP أو GIF');const name=hex(crypto.getRandomValues(new Uint8Array(16)))+'.'+ext;await env.DB.prepare('INSERT INTO uploads(name,mime,data,created_at) VALUES(?,?,?,?)').bind(name,mime,buf,Date.now()).run();return json({url:'/api/uploads/'+name},201);}
 if(p==='/api/admin/settings'&&m==='GET'){const socials=JSON.parse(await setting(env,'socials','{}')||'{}');return json({whatsapp_number:await setting(env,'whatsapp_number','971541494114'),wa_message:await setting(env,'wa_message'),phone:await setting(env,'phone'),email:await setting(env,'email'),address:await setting(env,'address'),hours:await setting(env,'hours'),socials:SOCIALS.map(([key,name])=>({key,name,url:(socials[key]||{}).url||'',on:(socials[key]||{}).on!==false}))});}
 if(p==='/api/admin/settings'&&m==='PUT'){const b=await bodyJson(request);const number=String(b?.whatsapp_number||'').replace(/\D/g,'');if(number.length<8||number.length>15)return fail('رقم واتساب غير صحيح');const email=String(b.email||'');if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return fail('البريد الإلكتروني غير صحيح');for(const [k,v] of Object.entries({whatsapp_number:number,wa_message:String(b.wa_message||'').slice(0,300),phone:String(b.phone||'').slice(0,40),email:email.slice(0,150),address:String(b.address||'').slice(0,200),hours:String(b.hours||'').slice(0,120)}))await setSetting(env,k,v);const socials={};for(const [key] of SOCIALS){const item=Array.isArray(b.socials)?b.socials.find(x=>x.key===key):null;if(item){const url=String(item.url||'');if(url&&!/^https?:\/\/[^\s]+$/i.test(url))return fail('الرابط يجب أن يبدأ بـ https://');socials[key]={url,on:item.on!==false};}}await setSetting(env,'socials',JSON.stringify(socials));return json({ok:true});}
 return fail('غير موجود',404);}
 return fail('غير موجود',404);
 }catch(e){return fail('حدث خطأ داخلي. راجع إعداد قاعدة البيانات وصلاحياتها.',500);}}
